DROP TABLE IF EXISTS order_items;

DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS saved_products;

DROP TABLE IF EXISTS cart_items;

DROP TABLE IF EXISTS carts;

DROP TABLE IF EXISTS products;

DROP TABLE IF EXISTS images;

DROP TABLE IF EXISTS customers;

DROP TABLE IF EXISTS websites;

DROP TABLE IF EXISTS admins;
